#!/bin/bash

echo "execute post install for ros-jazzy-sample-resnet101-quantized ..."
if [ -d "/opt/model" ]; then
    echo "model path /opt/model exit."
else
    echo "model path /opt/model not exit."
    sudo mkdir /opt/model    
fi
sudo wget https://huggingface.co/qualcomm/ResNet101Quantized/resolve/653916aac7c732d28863aa449176299ba2890c15/ResNet101Quantized.tflite?download=true -O /opt/model/ResNet101Quantized.tflite
sudo wget https://raw.githubusercontent.com/quic/ai-hub-models/refs/heads/main/qai_hub_models/labels/imagenet_labels.txt -O /opt/model/imagenet_labels.txt

echo "finish post install"

